package httpapi

import (
	"strings"
	"testing"

	"gitlab.com/dalibo/squishy/internal/translate"
)

// generatedOverridePlan is a plan shaped like sv_orders: one plain column,
// one refused generated column (CopiedGenerated, plain on PG) and one
// column PostgreSQL generates.
func generatedOverridePlan() *translate.SchemaPlan {
	return &translate.SchemaPlan{Tables: []translate.PGTable{
		{
			Schema: "mig", Name: "sv_orders",
			Columns: []translate.PGColumn{
				{Name: "id", Type: "BIGINT", NotNull: true, Identity: true},
				{Name: "paid", Type: "BOOLEAN", Default: "false", Collation: `"C"`, Check: "paid IS NOT NULL"},
				{Name: "paid_v", Type: "TEXT"},
				{Name: "total", Type: "NUMERIC(10,2)", Generated: &translate.PGGenerated{Expr: `"qty" * "unit_price"`, Stored: true}},
			},
			PK:              []string{"id"},
			CopiedGenerated: []string{"paid_v"},
		},
		{Schema: "mig", Name: "Other", Columns: []translate.PGColumn{{Name: "x", Type: "INTEGER"}}},
	}}
}

func TestGeneratedOverrideValidate(t *testing.T) {
	plan := generatedOverridePlan()
	cases := []struct {
		name    string
		in      []translate.GeneratedOverride
		wantErr string
	}{
		{"table missing", []translate.GeneratedOverride{{Table: "nope", Column: "paid_v", Expr: "'1'"}}, `table "nope" is not in the migration plan`},
		{"table case-sensitive", []translate.GeneratedOverride{{Table: "SV_ORDERS", Column: "paid_v", Expr: "'1'"}}, "is not in the migration plan"},
		{"column missing", []translate.GeneratedOverride{{Table: "sv_orders", Column: "nope", Expr: "'1'"}}, `has no column "nope"`},
		{"plain column", []translate.GeneratedOverride{{Table: "sv_orders", Column: "paid", Expr: "'1'"}}, "is not a generated column"},
		{"no table", []translate.GeneratedOverride{{Column: "paid_v", Expr: "'1'"}}, "table and column are required"},
		{"empty expression", []translate.GeneratedOverride{{Table: "sv_orders", Column: "paid_v"}}, "the expression is required"},
		{"blank expression", []translate.GeneratedOverride{{Table: "sv_orders", Column: "paid_v", Expr: " \n\t"}}, "the expression is empty"},
		{"clause escape", []translate.GeneratedOverride{{Table: "sv_orders", Column: "paid_v", Expr: "'x') STORED, \"y\" int GENERATED ALWAYS AS (1"}}, "unbalanced ')'"},
		{"second statement", []translate.GeneratedOverride{{Table: "sv_orders", Column: "paid_v", Expr: "'x'; DROP SCHEMA squishy"}}, "';'"},
		{"duplicate", []translate.GeneratedOverride{
			{Table: "sv_orders", Column: "paid_v", Expr: "'1'"},
			{Table: "sv_orders", Column: "PAID_V", Expr: "'2'"},
		}, "duplicate override of sv_orders.paid_v"},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			out, err := validateGeneratedOverrides(plan, c.in)
			if err == nil {
				t.Fatalf("expected an error containing %q, got %v", c.wantErr, out)
			}
			if !strings.Contains(err.Error(), c.wantErr) {
				t.Fatalf("error %q does not contain %q", err, c.wantErr)
			}
		})
	}
}

func TestGeneratedOverrideValidateHappyPath(t *testing.T) {
	plan := generatedOverridePlan()
	expr := `CASE WHEN "paid" THEN '1' ELSE '0' END  `
	out, err := validateGeneratedOverrides(plan, []translate.GeneratedOverride{
		{Table: "sv_orders", Column: "PAID_V", Expr: expr},
		{Table: "sv_orders", Column: "total", Expr: `"qty" * "unit_price" + 0`},
	})
	if err != nil {
		t.Fatal(err)
	}
	if len(out) != 2 {
		t.Fatalf("got %d overrides, want 2", len(out))
	}
	// Column takes the plan spelling; the expression is stored as given.
	if out[0] != (translate.GeneratedOverride{Table: "sv_orders", Column: "paid_v", Expr: expr}) {
		t.Fatalf("unexpected first override %+v", out[0])
	}
	if out[1].Column != "total" {
		t.Fatalf("unexpected second override %+v", out[1])
	}
	empty, err := validateGeneratedOverrides(plan, nil)
	if err != nil || empty == nil || len(empty) != 0 {
		t.Fatalf("empty list: got %v, %v; want [] and no error", empty, err)
	}
}

func TestGeneratedOverrideOverridableColumns(t *testing.T) {
	got := overridableColumns(generatedOverridePlan())
	want := []string{"sv_orders.paid_v", "sv_orders.total"}
	if strings.Join(got, ",") != strings.Join(want, ",") {
		t.Fatalf("overridable = %v, want %v", got, want)
	}
	if got := overridableColumns(&translate.SchemaPlan{}); got == nil || len(got) != 0 {
		t.Fatalf("empty plan: overridable = %v, want []", got)
	}
}

func TestGeneratedOverrideProbeDDL(t *testing.T) {
	plan := generatedOverridePlan()
	ov := translate.GeneratedOverride{Table: "sv_orders", Column: "paid_v", Expr: `CASE WHEN "paid" THEN '1' ELSE '0' END`}
	got, n := generatedProbeDDL(plan.Tables[0], []translate.GeneratedOverride{ov})
	// total stays generated by the plan's expression: PostgreSQL must see
	// it generated, or an override referencing it would pass the probe.
	want := `CREATE TABLE "pg_temp"."squishy_generated_probe" (
  "id" BIGINT,
  "paid" BOOLEAN,
  "paid_v" TEXT GENERATED ALWAYS AS (CASE WHEN "paid" THEN '1' ELSE '0' END) STORED,
  "total" NUMERIC(10,2) GENERATED ALWAYS AS ("qty" * "unit_price") STORED
);
`
	if got != want {
		t.Fatalf("probe DDL:\n%s\nwant:\n%s", got, want)
	}
	if n != 2 || strings.Count(got, "GENERATED") != 2 {
		t.Fatalf("probe DDL: generated = %d, %d GENERATED clauses; want 2 and 2", n, strings.Count(got, "GENERATED"))
	}
}

// TestGeneratedOverrideProbeDDLMatchesCreateDDL checks the probe table is
// generated like the table create_ddl will create for the whole request:
// two overrides (one referencing the other, which PostgreSQL must refuse)
// plus a column the plan generates and one it overrides, CopiedGenerated
// columns without an override left plain.
func TestGeneratedOverrideProbeDDLMatchesCreateDDL(t *testing.T) {
	tbl := translate.PGTable{
		Schema: "mig", Name: "sv_orders",
		Columns: []translate.PGColumn{
			{Name: "id", Type: "BIGINT", Identity: true},
			{Name: "paid", Type: "BOOLEAN"},
			{Name: "paid_c", Type: "TEXT"},
			{Name: "paid_v", Type: "TEXT"},
			{Name: "mark", Type: "TEXT"},
			{Name: "total_v", Type: "NUMERIC(10,2)", Generated: &translate.PGGenerated{Expr: `"qty" * "unit_price"`, Stored: true}},
			{Name: "total_s", Type: "NUMERIC(10,2)", Generated: &translate.PGGenerated{Expr: `"qty" + 1`, Stored: true}},
		},
		CopiedGenerated: []string{"paid_c", "paid_v", "mark"},
	}
	ovs := []translate.GeneratedOverride{
		{Table: "sv_orders", Column: "paid_c", Expr: `CASE WHEN "paid" THEN '1' ELSE '0' END`},
		{Table: "sv_orders", Column: "paid_v", Expr: `"paid_c" || 'x'`},
		{Table: "sv_orders", Column: "total_s", Expr: `"qty" + 2`},
	}
	got, n := generatedProbeDDL(tbl, ovs)
	want := `CREATE TABLE "pg_temp"."squishy_generated_probe" (
  "id" BIGINT,
  "paid" BOOLEAN,
  "paid_c" TEXT GENERATED ALWAYS AS (CASE WHEN "paid" THEN '1' ELSE '0' END) STORED,
  "paid_v" TEXT GENERATED ALWAYS AS ("paid_c" || 'x') STORED,
  "mark" TEXT,
  "total_v" NUMERIC(10,2) GENERATED ALWAYS AS ("qty" * "unit_price") STORED,
  "total_s" NUMERIC(10,2) GENERATED ALWAYS AS ("qty" + 2) STORED
);
`
	if got != want {
		t.Fatalf("probe DDL:\n%s\nwant:\n%s", got, want)
	}
	for _, clause := range []string{
		`"paid_c" TEXT GENERATED ALWAYS AS (CASE WHEN "paid" THEN '1' ELSE '0' END) STORED`,
		`"paid_v" TEXT GENERATED ALWAYS AS ("paid_c" || 'x') STORED`,
		`"total_v" NUMERIC(10,2) GENERATED ALWAYS AS ("qty" * "unit_price") STORED`,
		`"total_s" NUMERIC(10,2) GENERATED ALWAYS AS ("qty" + 2) STORED`,
	} {
		if !strings.Contains(got, clause) {
			t.Fatalf("probe DDL lacks %s:\n%s", clause, got)
		}
	}
	if n != 4 || strings.Count(got, "GENERATED") != 4 {
		t.Fatalf("probe DDL: generated = %d, %d GENERATED clauses; want 4 and 4", n, strings.Count(got, "GENERATED"))
	}
	if strings.Contains(got, `"qty" + 1`) {
		t.Fatalf("the plan expression of the overridden total_s leaked into the probe:\n%s", got)
	}
}

func TestGeneratedOverrideByTable(t *testing.T) {
	groups := overridesByTable([]translate.GeneratedOverride{
		{Table: "b", Column: "x"}, {Table: "a", Column: "y"}, {Table: "b", Column: "z"},
	})
	if len(groups) != 2 || len(groups[0]) != 2 || len(groups[1]) != 1 ||
		groups[0][0].Column != "x" || groups[0][1].Column != "z" || groups[1][0].Table != "a" {
		t.Fatalf("unexpected grouping %+v", groups)
	}
	if got := overrideObjects(groups[0]); got != "b.x, b.z" {
		t.Fatalf("overrideObjects = %q", got)
	}
}
