package httpapi

// Generated-column overrides (MySQL / MariaDB sources).
//
//	GET /api/v1/migrations/{migrationID}/generated-overrides
//	    → {"migration_id", "overrides": [{table, column, expression}],
//	       "overridable": ["<table>.<column>", …], "plan_required": bool}
//	PUT /api/v1/migrations/{migrationID}/generated-overrides
//	    body {"overrides": [{table, column, expression}]} — replaces the
//	    whole list ([] clears it; clients merge per column).
//	    → 200 {"overrides": […], "validated": true, "replan_required": true}
//
// An override is the PostgreSQL generation expression of one generated
// column of the source (see internal/translate/mysql_generated_override.go).
// The PUT refuses (400) an override whose table is not in the plan, whose
// column is not in that table or is not generated, whose expression is
// blank or leaves its clause (translate.ValidateGeneratedOverrideExpr), a
// duplicate of the same column, and — the semantic check — an expression
// PostgreSQL itself rejects: each table with overrides is tried once on
// the target PostgreSQL in a rolled-back CREATE TABLE of a temporary copy
// of that table (syntax, types, unknown columns, non-immutable functions
// such as concat_ws, a reference to another generated column). The
// migration must be planned (409 otherwise), and the stored overrides only
// take effect on the next POST /plan.
//
// The probe table is the table create_ddl will create for the requested
// list, as far as generation goes: a column overridden by the request is
// generated by its override, a column the plan already generates (and the
// request does not override) keeps the plan's expression, every other
// column (ordinary, or refused and copied — CopiedGenerated) is plain.
// This deliberately departs from "leave the other generated columns
// plain": that would accept an override referencing a generated column,
// which PostgreSQL forbids ("cannot use generated column … in column
// generation expression") and create_ddl would then fail on — MySQL
// allows it, so overrides copied from the source hit it. The probe runs
// under create_ddl's search_path (<target schema>, public; see
// translate.buildDDL). Known limits: a column whose plan expression came
// from a stored override the request drops is probed with that stale
// expression until the next POST /plan (this can only make the probe
// stricter); extension types or functions missing from the target
// database (PostGIS, …) fail the probe as they would fail create_ddl.

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"

	"gitlab.com/dalibo/squishy/internal/connection"
	"gitlab.com/dalibo/squishy/internal/dialects"
	pgast "gitlab.com/dalibo/squishy/internal/dialects/postgres"
	"gitlab.com/dalibo/squishy/internal/project"
	"gitlab.com/dalibo/squishy/internal/translate"
)

// generatedProbeTable is the temporary table the PostgreSQL probe creates
// (in pg_temp, inside a transaction that is always rolled back).
const generatedProbeTable = "squishy_generated_probe"

// overrideRejectedError is a probe failure caused by the override itself
// (PostgreSQL refused the DDL, or the created table is not the expected
// one) rather than by the connection: the handler answers 400, not 502.
type overrideRejectedError struct{ msg string }

func (e *overrideRejectedError) Error() string { return e.msg }

// getGeneratedOverrides returns the overrides stored on the migration and
// the columns an override may target in its current plan.
func (d *Deps) getGeneratedOverrides(w http.ResponseWriter, r *http.Request) {
	m, inst, err := d.loadMigrationWithInstance(r.Context(), chi.URLParam(r, "migrationID"))
	if err != nil {
		writeMigErr(w, err)
		return
	}
	overrides := []translate.GeneratedOverride{}
	if len(m.GeneratedOverrides) > 0 {
		if err := json.Unmarshal(m.GeneratedOverrides, &overrides); err != nil {
			errJSON(w, http.StatusInternalServerError, "malformed generated_overrides stored on the migration: "+err.Error())
			return
		}
	}
	overridable := []string{}
	planRequired := m.Status != "planned"
	if !planRequired && overridesApply(inst) {
		plan, err := migrationPlan(m)
		if err != nil {
			errJSON(w, http.StatusInternalServerError, err.Error())
			return
		}
		overridable = overridableColumns(plan)
	}
	okJSON(w, map[string]any{
		"migration_id":  m.ID,
		"overrides":     overrides,
		"overridable":   overridable,
		"plan_required": planRequired,
	})
}

// setGeneratedOverrides validates and stores the whole override list.
func (d *Deps) setGeneratedOverrides(w http.ResponseWriter, r *http.Request) {
	m, inst, err := d.loadMigrationWithInstance(r.Context(), chi.URLParam(r, "migrationID"))
	if err != nil {
		writeMigErr(w, err)
		return
	}
	var req struct {
		Overrides *[]translate.GeneratedOverride `json:"overrides"`
	}
	dec := json.NewDecoder(r.Body)
	dec.DisallowUnknownFields()
	if err := dec.Decode(&req); err != nil {
		errJSON(w, http.StatusBadRequest, "invalid JSON: "+err.Error())
		return
	}
	if req.Overrides == nil {
		errJSON(w, http.StatusBadRequest, `"overrides" is required (send [] to delete every override)`)
		return
	}
	if m.Status != "planned" {
		errJSON(w, http.StatusConflict, "plan the migration first")
		return
	}
	if len(*req.Overrides) > 0 && !overridesApply(inst) {
		errJSON(w, http.StatusBadRequest, "generation expression overrides apply only to MySQL / MariaDB sources (this instance is "+inst.Kind+")")
		return
	}
	plan, err := migrationPlan(m)
	if err != nil {
		errJSON(w, http.StatusInternalServerError, err.Error())
		return
	}
	validated, err := validateGeneratedOverrides(plan, *req.Overrides)
	if err != nil {
		errJSON(w, http.StatusBadRequest, err.Error())
		return
	}

	if len(validated) > 0 {
		ctx, cancel := context.WithTimeout(r.Context(), 30*time.Second)
		defer cancel()
		pool, err := connection.OpenPostgres(ctx, connection.Params{
			Kind: "postgres", Host: inst.TargetHost, Port: inst.TargetPort,
			Database: inst.TargetDatabase, Username: inst.TargetUsername,
			Password: inst.TargetPassword, SSLMode: inst.TargetSSLMode,
		})
		if err != nil {
			errJSON(w, http.StatusBadGateway, "cannot reach the target PostgreSQL to validate the override: "+err.Error())
			return
		}
		defer pool.Close()
		for _, group := range overridesByTable(validated) {
			tbl := planTable(plan, group[0].Table)
			if err := probeGeneratedOverrides(ctx, pool, m.TargetSchemaName, *tbl, group); err != nil {
				var rejected *overrideRejectedError
				if errors.As(err, &rejected) {
					errJSON(w, http.StatusBadRequest, err.Error())
				} else {
					errJSON(w, http.StatusBadGateway, "cannot validate the override on the target PostgreSQL: "+err.Error())
				}
				return
			}
		}
	}

	raw, err := json.Marshal(validated)
	if err != nil {
		errJSON(w, http.StatusInternalServerError, err.Error())
		return
	}
	if err := d.Repo.SetGeneratedOverrides(r.Context(), m.ID, raw); err != nil {
		if errors.Is(err, project.ErrNotFound) {
			errJSON(w, http.StatusNotFound, "migration not found")
			return
		}
		errJSON(w, http.StatusInternalServerError, err.Error())
		return
	}
	okJSON(w, map[string]any{
		"overrides":       validated,
		"validated":       true,
		"replan_required": true,
	})
}

// overridesApply reports whether the translator consults generation
// expression overrides for this instance's source: only the MySQL /
// MariaDB generated-column pass does (mysql_generated.go); on any other
// source an override would match nothing and be reported unused.
func overridesApply(inst *project.Instance) bool {
	return dialects.IsMySQLFamily(dialects.Kind(inst.Kind))
}

// migrationPlan decodes the target plan persisted by POST /plan.
func migrationPlan(m *project.Migration) (*translate.SchemaPlan, error) {
	var plan translate.SchemaPlan
	if len(m.TargetPlan) > 0 {
		if err := json.Unmarshal(m.TargetPlan, &plan); err != nil {
			return nil, fmt.Errorf("malformed target_plan stored on the migration: %w", err)
		}
	}
	return &plan, nil
}

// planTable returns the plan table named exactly name (the plan keeps the
// source spelling, which the translator matches exactly), or nil.
func planTable(plan *translate.SchemaPlan, name string) *translate.PGTable {
	for i := range plan.Tables {
		if plan.Tables[i].Name == name {
			return &plan.Tables[i]
		}
	}
	return nil
}

// overridableColumns lists "<table>.<column>" for every column an
// override may target: the generated columns squishy refused (created
// plain and copied, CopiedGenerated) and the columns PostgreSQL generates
// (translated automatically, or already overridden).
func overridableColumns(plan *translate.SchemaPlan) []string {
	out := []string{}
	for i := range plan.Tables {
		tbl := &plan.Tables[i]
		for _, c := range tbl.Columns {
			if columnOverridable(tbl, c) {
				out = append(out, tbl.Name+"."+c.Name)
			}
		}
	}
	return out
}

func columnOverridable(tbl *translate.PGTable, c translate.PGColumn) bool {
	if c.Generated != nil {
		return true
	}
	for _, name := range tbl.CopiedGenerated {
		if name == c.Name {
			return true
		}
	}
	return false
}

// validateGeneratedOverrides checks a requested override list against the
// plan, without touching any database. Each override must name a plan
// table exactly and one of its overridable columns (compared
// case-insensitively, as MySQL does; the returned entry carries the
// plan's spelling), carry a non-blank expression that stays inside its
// clause, and target a column no other override targets. The expression
// text is returned exactly as given.
func validateGeneratedOverrides(plan *translate.SchemaPlan, in []translate.GeneratedOverride) ([]translate.GeneratedOverride, error) {
	out := make([]translate.GeneratedOverride, 0, len(in))
	for i, ov := range in {
		where := fmt.Sprintf("override %d (%s.%s)", i, ov.Table, ov.Column)
		if ov.Table == "" || ov.Column == "" {
			return nil, fmt.Errorf("override %d: table and column are required", i)
		}
		tbl := planTable(plan, ov.Table)
		if tbl == nil {
			return nil, fmt.Errorf("%s: table %q is not in the migration plan (table names are case-sensitive)", where, ov.Table)
		}
		col := -1
		for j := range tbl.Columns {
			// Single identifier, MySQL column names are case-insensitive.
			if strings.EqualFold(tbl.Columns[j].Name, ov.Column) {
				col = j
				break
			}
		}
		if col < 0 {
			return nil, fmt.Errorf("%s: table %s has no column %q", where, tbl.Name, ov.Column)
		}
		if !columnOverridable(tbl, tbl.Columns[col]) {
			return nil, fmt.Errorf("%s: column %s.%s is not a generated column, only generated columns take a generation expression override", where, tbl.Name, tbl.Columns[col].Name)
		}
		if ov.Expr == "" {
			return nil, fmt.Errorf("%s: the expression is required", where)
		}
		if err := translate.ValidateGeneratedOverrideExpr(ov.Expr); err != nil {
			return nil, fmt.Errorf("%s: %w", where, err)
		}
		v := translate.GeneratedOverride{Table: tbl.Name, Column: tbl.Columns[col].Name, Expr: ov.Expr}
		for _, prev := range out {
			if prev.Table == v.Table && prev.Column == v.Column {
				return nil, fmt.Errorf("%s: duplicate override of %s.%s, keep exactly one", where, v.Table, v.Column)
			}
		}
		out = append(out, v)
	}
	return out, nil
}

// overridesByTable groups validated overrides per table, tables in order
// of first appearance and overrides in request order.
func overridesByTable(ovs []translate.GeneratedOverride) [][]translate.GeneratedOverride {
	var out [][]translate.GeneratedOverride
	idx := map[string]int{}
	for _, ov := range ovs {
		i, ok := idx[ov.Table]
		if !ok {
			i = len(out)
			idx[ov.Table] = i
			out = append(out, nil)
		}
		out[i] = append(out[i], ov)
	}
	return out
}

// generatedProbeDDL renders, with the typed pgast writer, the temporary
// table the probe creates for tbl and its overrides ovs (all on tbl,
// column names in the plan spelling — validateGeneratedOverrides): every
// column of tbl with its type only (no default, identity, check or
// collation); a column is generated by its override when ovs has one,
// else by the plan's expression when the plan generates it, else plain.
// generated is the number of generated columns of the probe table.
func generatedProbeDDL(tbl translate.PGTable, ovs []translate.GeneratedOverride) (ddl string, generated int) {
	cols := make([]pgast.ColumnDef, 0, len(tbl.Columns))
	for _, c := range tbl.Columns {
		def := pgast.ColumnDef{Name: c.Name, Type: c.Type}
		overridden := false
		for _, ov := range ovs {
			if ov.Column == c.Name {
				def.Generated = &pgast.GeneratedCol{Expr: ov.Expr}
				overridden = true
				break
			}
		}
		if !overridden && c.Generated != nil {
			def.Generated = &pgast.GeneratedCol{Expr: c.Generated.Expr}
		}
		if def.Generated != nil {
			generated++
		}
		cols = append(cols, def)
	}
	return pgast.Write([]pgast.Stmt{&pgast.CreateTable{
		Schema: "pg_temp", Name: generatedProbeTable, Columns: cols,
	}}), generated
}

// overrideObjects names the overridden columns, "<table>.<column>, …".
func overrideObjects(ovs []translate.GeneratedOverride) string {
	names := make([]string, len(ovs))
	for i, ov := range ovs {
		names[i] = ov.Table + "." + ov.Column
	}
	return strings.Join(names, ", ")
}

// probeGeneratedOverrides asks the target PostgreSQL whether it accepts
// the overrides ovs of tbl: under create_ddl's search_path (targetSchema,
// public) it creates the temporary copy of tbl rendered by
// generatedProbeDDL, checks that the created table has exactly tbl's
// columns and the expected number of generated ones (an expression text
// that closed the clause and smuggled extra clauses would not), and always
// rolls back. The DDL goes through the extended protocol, which refuses
// more than one statement. A PostgreSQL refusal of the DDL is returned as
// a *overrideRejectedError naming the table's overridden columns; a
// missing privilege (SQLSTATE 42501, e.g. no TEMPORARY privilege on the
// database) or any other error is an environment problem, not a verdict
// on the expression.
func probeGeneratedOverrides(ctx context.Context, pool *pgxpool.Pool, targetSchema string, tbl translate.PGTable, ovs []translate.GeneratedOverride) error {
	conn, err := pool.Acquire(ctx)
	if err != nil {
		return err
	}
	defer conn.Release()
	tx, err := conn.Begin(ctx)
	if err != nil {
		return err
	}
	defer func() { _ = tx.Rollback(context.Background()) }()

	if targetSchema == "" {
		targetSchema = tbl.Schema
	}
	if targetSchema != "" {
		// SET (not LOCAL) inside the transaction: the rollback undoes it.
		setPath := pgast.Write([]pgast.Stmt{&pgast.SetSearchPath{Schema: targetSchema, Additional: []string{"public"}}})
		if _, err := tx.Conn().PgConn().ExecParams(ctx, setPath, nil, nil, nil, nil).Close(); err != nil {
			return err
		}
	}

	objs := overrideObjects(ovs)
	ddl, wantGenerated := generatedProbeDDL(tbl, ovs)
	if _, err := tx.Conn().PgConn().ExecParams(ctx, ddl, nil, nil, nil, nil).Close(); err != nil {
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) {
			if pgErr.Code == "42501" {
				return fmt.Errorf("the target PostgreSQL user may not create the temporary probe table (%s, SQLSTATE %s); grant it TEMPORARY on the target database", pgErr.Message, pgErr.Code)
			}
			return &overrideRejectedError{msg: "override for " + objs + " rejected by PostgreSQL: " + pgErr.Message}
		}
		return err
	}
	var total, generated int
	// table_name is generatedProbeTable.
	if err := tx.QueryRow(ctx, `
		SELECT count(*), count(*) FILTER (WHERE is_generated = 'ALWAYS')
		  FROM information_schema.columns
		 WHERE table_schema LIKE 'pg\_temp%' AND table_name = 'squishy_generated_probe'`).
		Scan(&total, &generated); err != nil {
		return err
	}
	if total != len(tbl.Columns) || generated != wantGenerated {
		return &overrideRejectedError{msg: fmt.Sprintf("override for %s rejected: an expression does not stay one generation expression (the probe table has %d columns, %d generated; expected %d and %d)",
			objs, total, generated, len(tbl.Columns), wantGenerated)}
	}
	return nil
}
